### PR TITLE
Pm 15 tatsat jha neh waiver

### PR DESCRIPTION
**Pull request by TatsatJha**
image
image
This should be the last fix needed for this. These are the disclaimer messages I'm seeing on my side. I'll have this be a draft just in case.

### CODE REVIEW

**Comment by jdamerow** [comment]
Let's do it right :)
https://github.com/halogenica/beautifulhugo?tab=readme-ov-file#site-disclaimer

You probably want to add a `static/css/main.css` and override the disclaimer class.

**Comment by TatsatJha** [comment]
okay that's not what I wanted to happen but I think I know how to fix it now

**Comment by TatsatJha** [comment]
It looks like none of the styles I add are doing anything so I'm not sure what to do outside of cloning the beautiful hugo submodule and it editing the main.css in the actual theme

**Comment by jdamerow** [comment]
Same thing here, there are also path issues but this should work after merging.

**Pull request merged**
