### PR TITLE
[DHReSCUnit/project-management#22] Add title meta data 

### PR DESCRIPTION
**Pull request by TatsatJha**
I believe this is the correct way of going about this, I did the same thing for the custom footer.

### CODE REVIEW

**Comment by jdamerow** [comment]
Hm, not sure. Have you tried setting the `homeTitle` property?
https://github.com/DHReSCUnit/dhrescunit.github.io/blob/main/hugo.toml#L25

**Comment by TatsatJha** [comment]
I was just using the regular title property, but I can utilize home title if we want to have it be different on the home page

**Comment by jdamerow** [comment]
what I meant is, that it should do this by itself already if you set the right property? it works for posts, doesn't it?

**Comment by TatsatJha** [comment]
This is correct, I'll push the proper commit

**Pull request merged**
